jdbc:
    driverClassName: com.mysql.jdbc.Driver
    password: 1.0
    url: jdbc:mysql://192.168.3.213:3306/taotao?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root

